time_duration = 3
time_duration_2 = 8
time_duration_menu = 0.3
time_duration_fin = 60

#Aquí se encuentran todas las opciones para las preguntas
color_verde = str("1. Verde")
color_azul = str("2. Azul")
color_amarillo = str("3. Amarillo")
color_marron = str("4. Marron")
enhorabuena = str("Enhorabuena, respuesta correcta")
siguiente_preg = str("Siguiente pregunta")
respuesta_inc = str("respuesta incorrecta")
lista_colores = [color_verde, color_azul, color_amarillo, color_marron]
logo_xiaomi = str("3. Xiaomi")
logo_samsung = str("2. Samsung")
logo_lg = str("1. LG")
logo_sony = str("4. Sony")
lista_logotipos = [logo_lg,logo_samsung,logo_xiaomi,logo_sony]
estrellas_248 = str("1. 248")
estrellas_una = str("2. Solamente hay una")
estrellas_demasiadas = str("3. Demasiadas para ser contadas")
estrellas_none = str("4. No hay")
lista_estrellas = [estrellas_248, estrellas_una, estrellas_demasiadas, estrellas_none]
pena_blanca = str("1. Peñas blancas")
pena_akina = str("2. Monte Akina")
pena_bermeja = str("3. Peña  bermeja")
pena_rosada = str("4. Peña rosada")
lista_pena = [pena_blanca, pena_akina, pena_bermeja, pena_rosada]
marca_toyota = str("4. Toyota")
marca_bmw = str("2. BMW")
marca_hyundai = str("3. Hyundai")
marca_pontiac = str("1. Pontiac")
lista_marcas_coche = [marca_pontiac, marca_bmw, marca_hyundai, marca_toyota]
traccion_delantera = ("1. Motor delante, tracción delante")
traccion_todoterreno = ("2. Todoterreno")
traccion_descapotable = ("3. Descapotable")
traccion_nada = ("4. No tiene significado")
lista_traccion = [traccion_delantera, traccion_todoterreno, traccion_descapotable, traccion_nada]
nombre_reality_trent = str("1. Trent")
nombre_reality_gwen = str("2. Gwen")
nombre_reality_owen = str("3. Owen")
nombre_reality_scott = str("4. Scott")
lista_nombres_reality = [nombre_reality_trent, nombre_reality_gwen, nombre_reality_owen, nombre_reality_scott]
youtuber_alvamajo = str("3. Alva Majo")
youtuber_guinxu = str("2. Guinxu")
youtuber_rubius = str("1. El Rubius")
youtuber_ibai = str("4. Ibai")
lista_youtube = [youtuber_rubius, youtuber_guinxu, youtuber_alvamajo, youtuber_ibai]
cantante_daftpunk = str("1. Daft Punk")
cantante_davidguetta = str("2. David Guetta")
cantante_stromae = str("3. Stromae")
cantante_edithpiaf = str("4. Edith Piaf")
lista_cantantes_franceses = [cantante_daftpunk, cantante_davidguetta, cantante_stromae, cantante_edithpiaf]
ciudad_madrid = str("1. Madrid")
ciudad_budapest = str("2. Budapest")
ciudad_roma = str("3. Roma")
ciudad_algeciras = str("4. Algeciras")
lista_capitales = [ciudad_madrid, ciudad_budapest, ciudad_roma, ciudad_algeciras]
pk_vaporeon = str("1. Vaporeon")
pk_littleo = str("2. Littleo")
pk_xerneas = str("3. Xerneas")
pk_voltorb = str("4. Voltorb")
lista_pk = [pk_vaporeon, pk_littleo, pk_xerneas, pk_voltorb]
cic_quintana = str("1. Quintana")
cic_nibali = str("2. Nibali")
cic_bardet = str("3. Bardet")
cic_pinot = str("4. Pinot")
lista_cic = [cic_quintana, cic_nibali, cic_bardet, cic_pinot]
len_python = str("1. Python")
len_c = str("2. C++")
len_java = str("3. Java")
len_no = str("4. En nada")
lista_len = [len_python, len_c, len_java, len_no]
mc_pitbull = str("1. Pitbull")
mc_eminem = str("2. Eminem")
mc_kevinho = str("3. Mc Kevinho")
mc_thegame = str("4. The Game")
lista_mc = [mc_pitbull, mc_eminem, mc_kevinho, mc_thegame]
ano_1789 = str("1. 1789")
ano_1192 = str("2. 1192")
ano_1482 = str("3. 1482")
ano_20 = str("4. 20")
lista_ano = [ano_1789, ano_1192, ano_1482, ano_20]
namae_white = str("1. White")
namae_blanco = str("2. Blanco")
namae_cesar = str("3. Cesar")
namae_black = str("4. Black")
lista_namae = [namae_white, namae_blanco, namae_cesar, namae_black]
pil_alonso = str("1. Alonso")
pil_delarosa = str("2. De La Rosa")
pil_rodriguez = str("3. Rodríguez")
pil_gene = str("4. Gené")
lista_pil = [pil_alonso, pil_delarosa, pil_rodriguez, pil_gene]


#En esta zona se experimenta para conseguir el sistema de aciertos
a = 0
b = 0
resp_cor = 0
resp_incor = 0
respuesta_correcta = a+1
